"""add is_active field

Revision ID: d939f93bf0c8
Revises: 3287a8b856ee
Create Date: 2026-02-25 20:24:16.374002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd939f93bf0c8'
down_revision: Union[str, Sequence[str], None] = '3287a8b856ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('model_version', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('model_version', 'is_active')
    op.drop_column('conversations', 'is_active')
    # ### end Alembic commands ###
